---
apiVersion: aws.platform.upbound.io/v1alpha1
kind: XPodIdentity
metadata:
  name: external-dns
  labels:
    app.kubernetes.io/instance: external-dns
    app.kubernetes.io/managed-by: platform
    app.kubernetes.io/name: external-dns
    app.kubernetes.io/part-of: external-dns
  annotations:
    argo-cd.argoproj.io/sync-wave: "-10"
spec:
  parameters:
    ## The cluster name
    clusterName: CLUSTER_NAME
    ## The region to deploy the resources
    region: REGION
    ## The service account to associate the permissions
    serviceAccount:
      name: external-dns
      namespace: external-dns
    ## The policy to attach to the role
    inlinePolicy:
      - name: default
        policy: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": [
                  "route53:ChangeResourceRecordSets"
                ],
                "Resource": [
                  "arn:aws:route53:::hostedzone/*"
                ]
              },
              {
                "Effect": "Allow",
                "Action": [
                  "route53:ListHostedZones",
                  "route53:ListResourceRecordSets",
                  "route53:ListTagsForResource"
                ],
                "Resource": ["*"]
              }
            ]
          }
