---
##
## The sole purpose of this application is to keep the cluster
## definition up to date in the cluster.
##
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-registration
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  ## Source in the tenant repository and provision a cluster from the values
  ## defined in the cluster definition. Again we use the platform config plugin
  ## to inject the repository and revision values; ensuring everything is
  ## driven by the source of truth.
  # NOTE: Be careful changes the generators as the values are patched
  project: system
  sources:
    - repoURL: PLATFORM_REPO
      targetRevision: PLATFORM_REPO_REVISION
      path: charts/cluster-registration
      helm:
        releaseName: cluster-registration
        values: |
          revision_overrides::
            platform: "ignore"
            tenant: "ignore"
        valueFiles:
          - "$values/clusters/{{ .cluster_name }}.yaml"
    - repoURL: TENANT_REPO
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 20s
        maxDuration: 1m
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
