---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secrets-store
  namespace: external-secrets
  annotations:
    app.kubernetes.io/managed-by: argocd
spec:
  provider:
    aws:
      service: SecretsManager
      region: PATCH_ME
