---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workloads
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    kustomize.appset.repository: tenant
spec:
  goTemplate: true

  ## Add a strategy permiting us to control the ordering of resources
  ## by using labelling.
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: phase
              operator: In
              values:
                - primary
        - matchExpressions:
            - key: phase
              operator: In
              values:
                - secondary
        - matchExpressions:
            - key: phase
              operator: NotIn
              values:
                - primary
                - secondary

  # Generate applications from the shared services repository
  generators:
    - git:
        repoURL: TENANT_REPO
        revision: HEAD
        files:
          - path: "workloads/applications/**/{{ .environment }}.yaml"
      plugin:
        name: argocd-platform-config
      ## Filter on only those files with the correct values
      selector:
        matchExpressions:
          - key: helm.chart
            operator: Exists
          - key: helm.version
            operator: Exists
          - key: helm.repository
            operator: Exists

  ## Sync Policy for the ApplicationSet
  syncPolicy:
    # Prevents ApplicationSet controller from modifying Applications. Delete is allowed.
    applicationsSync: create-delete
    # Prevent an Application's child resources from being deleted, when the parent Application is deleted
    # preserveResourcesOnDeletion: true

  ## Template out an application for each of the tenant applications
  template:
    metadata:
      name: "workloads-applications-{{ .path.basenameNormalized }}"
      namespace: argocd
      labels:
        app.kubernetes.io/name: argocd
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/instance: argocd
        app.kubernetes.io/part-of: argocd
        app.kubernetes.io/environment: "{{ .values.environment }}"
        app.kubernetes.io/type: helm
        phase: secondary

    spec:
      project: applications
      sources:
        - repoURL: "{{ .helm.repository }}"
          targetRevision: "{{ .helm.version }}"
          chart: "{{ .helm.chart }}"
          helm:
            releaseName: "{{ default .path.basenameNormalized .helm.releaseName }}"
            valueFiles:
              - "$values/{{ .path.path }}/values/all.yaml"
              - "$values/{{ .path.path }}/values/{{ .values.environment }}.yaml"
            ignoreMissingValueFiles: true
        - repoURL: "{{ .values.repository }}"
          targetRevision: "{{ .values.revision }}"
          ref: values

      ## Destination is the cluster to deploy to
      destination:
        server: https://kubernetes.default.svc
        ## /applications/[1]/DIRECTORY/FILE.yaml
        namespace: "{{ default (index .path.segments 1) .helm.namespace }}"

      ## Sync policy for the application
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        retry:
          backoff:
            duration: '{{ default "180s" .sync.retryBackoff }}'
            maxDuration: '{{ default "5m" .sync.retryMaxDuration }}'
        # Use server-side apply for better efficiency and interop
        # between controllers making partial changes to manifests.
        # Also enable apply out of sync only rather than trying to
        # apply all resources in the application.
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - ApplyOutOfSyncOnly=true
