---
##
## This application set is used to create Applications for each of the
## platform kustomize charts, defined in the ./platform directory.
##
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system-kustomize
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    kustomize.patch.appset.platform: "true"
spec:
  goTemplate: true

  ## Add a strategy permiting us to control the ordering of resources
  ## by using labelling.
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: phase
              operator: In
              values:
                - primary
        - matchExpressions:
            - key: phase
              operator: In
              values:
                - secondary
        - matchExpressions:
            - key: phase
              operator: NotIn
              values:
                - primary
                - secondary

  ## Generate applications from the platform repository
  ## NOTICE: These generators are patched in the kustomize/overlays/release/platform.yaml
  ## file. So if you are making any changes here, please make sure to update the overlay file.
  generators:
    - matrix:
        generators:
          - git:
              repoURL: PLATFORM_REPO
              revision: PLATFORM_REVISION
              files:
                - path: "addons/kustomize/{{ .metadata.annotations.cloud_vendor }}/**/kustomize.yaml"
                - path: "addons/kustomize/oss/**/kustomize.yaml"
            selector:
              matchExpressions:
                - key: kustomize.path
                  operator: Exists
                - key: kustomize.feature
                  operator: Exists
                - key: namespace.name
                  operator: Exists
          - clusters:
              selector:
                matchExpressions:
                  - key: environment
                    operator: Exists
                  - key: "enable_{{ .kustomize.feature }}"
                    operator: In
                    values: ["true"]

  ## Sync Policy for the ApplicationSet
  syncPolicy:
    # Prevents ApplicationSet controller from modifying Applications. Delete is allowed.
    applicationsSync: create-delete

  ## Template out an application for each of the tenant applications
  template:
    metadata:
      name: "system-kust-{{ .path.basenameNormalized }}-{{ .metadata.labels.cluster_name }}"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: '{{ default "15" .sync.wave }}'
      labels:
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/name: "{{ normalize (default .feature .release_name) }}"
        app.kubernetes.io/type: kustomize
        phase: '{{ default "primary" .sync.phase }}'

    spec:
      ## The project to use for the application
      project: system

      ## The sources to use for the application
      source:
        repoURL: "{{ .metadata.annotations.platform_repository }}"
        targetRevision: "{{ .metadata.annotations.platform_revision }}"
        path: '{{ printf "%s/%s" .path.path .kustomize.path }}'
        kustomize: {}

      ## Destination is the cluster to deploy to
      destination:
        server: "{{ .server }}"
        ## /applications/TYPE/[2]/FILE.yaml or .helm.namespace
        namespace: "{{ .namespace.name }}"

      ## Sync policy for the application
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        retry:
          backoff:
            duration: '{{ default "30s" .sync.duration }}'
            maxDuration: '{{ default "5m" .sync.max_duration }}'
          limit: 10
        # Use server-side apply for better efficiency and interop
        # between controllers making partial changes to manifests.
        # Also enable apply out of sync only rather than trying to
        # apply all resources in the application.
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true

  ## If a kustomize.repository is defines we use the environment as the targetRevision. Its
  ## the responsibility of the repository to control the floating revisions.
  templatePatch: |
    {{- if and .kustomize.patches (gt (len .kustomize.patches) 0) }}
    ## Save the context for the dig function
    {{- $context := toJson . | fromJson }}
    spec:
      source:
        kustomize:
          patches:
            {{- range $change := .kustomize.patches }}
            - target:
                kind: {{ $change.target.kind }}
                name: {{ $change.target.name }}
              {{- range $patch := $change.patch }}
              {{- $params := splitList "." $patch.key }}
              {{- $value := $patch.default }}
              patch: |
                - op: {{ $patch.op }}
                  path: {{ $patch.path }}
                  {{- if eq (len $params) 1 }}
                  {{- $value = dig (index $params 0) "" $context }}
                  {{- else if eq (len $params) 2 }}
                  {{- $value = dig (index $params 0) (index $params 1) "" $context }}
                  {{- else if eq (len $params) 3 }}
                  {{- $value = dig (index $params 0) (index $params 1) (index $params 2) "" $context }}
                  {{- else if eq (len $params) 4 }}
                  {{- $value = dig (index $params 0) (index $params 1) (index $params 2) (index $params 3) "" $context }}
                  {{- end }}
                  value: {{ default $patch.default $value }}
              {{- end }}
            {{- end }}
    {{- end }}
