---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
  labels:
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: gp3
    app.kubernetes.io/part-of: platform
  annotations:
    ## Set at the default storage class
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  ## The file system type of the storage class
  fsType: ext4
  ## The encryption configuration
  encrypted: "true"
  ## The type of the storage class
  type: gp3
## The provisioner of the storage class
provisioner: kubernetes.io/aws-ebs
## The reclaim policy of the storage class
reclaimPolicy: Delete
## Binding mode
volumeBindingMode: WaitForFirstConsumer
