---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: amd64
  labels:
    karpenter.sh/nodepool: amd64
    karpenter.sh/nodepool-class: default
  annotations:
    karpenter.sh/nodepool-version: "1.2.1"
    karpenter.sh/nodepool-provider: aws
spec:
  template:
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default
      requirements:
        - key: "eks.amazonaws.com/instance-category"
          operator: In
          values: ["c", "m", "r"]
        - key: "eks.amazonaws.com/instance-cpu"
          operator: In
          values: ["4", "8", "16", "32"]
        - key: "eks.amazonaws.com/instance-generation"
          operator: Gt
          values: ["4"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand", "reserved"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
  ## The weight for the node pool
  weight: 100
  ## The disruption settings for the node pool
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: arm64
  labels:
    karpenter.sh/nodepool: graviton
    karpenter.sh/nodepool-class: default
  annotations:
    karpenter.sh/nodepool-version: "1.2.1"
    karpenter.sh/nodepool-provider: aws
spec:
  template:
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default
      requirements:
        - key: "eks.amazonaws.com/instance-category"
          operator: In
          values: ["c", "m", "r"]
        - key: "eks.amazonaws.com/instance-cpu"
          operator: In
          values: ["4", "8", "16", "32"]
        - key: "eks.amazonaws.com/instance-generation"
          operator: Gt
          values: ["4"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["spot", "on-demand", "reserved"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["arm64"]
  ## The weight for the node pool
  weight: 50
  ## The disruption settings for the node pool
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s
