---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
spec:
  description: >
    The project used by all the tenant applications
  sourceRepos:
    - "*"
  ## List of destinations we are permitted to create
  ## resources in
  destinations:
    - namespace: "!kube-system"
      server: "*"
    - namespace: "!argocd"
      server: "*"
    - namespace: "!default"
      server: "*"
    - namespace: "!kube-public"
      server: "*"
    - namespace: "!kube-node-lease"
      server: "*"
    - namespace: "*"
      server: https://kubernetes.default.svc
  ## List of resources we are not permitted to create
  clusterResourceBlacklist:
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: apps
      kind: Daemonsets
    - group: kyverno
      kind: ClusterPolicy
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - kind: RuntimeClass
      group: node.k8s.io
    - kind: ValidatingWebhookConfiguration
      group: admissionregistration.k8s.io
    - kind: MutatingWebhookConfiguration
      group: admissionregistration.k8s.io
    - kind: ArgoprojProject
      group: argoproj.io
  ## List of resources we are permitted to create
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: >
    The project used to configure additional platform level resources
  sourceRepos:
    - "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  clusterResourceBlacklist:
    - kind: ArgoprojProject
      group: argoproj.io
  destinations:
    - namespace: "!default"
      server: "*"
    - namespace: "!kube-public"
      server: "*"
    - namespace: "!kube-node-lease"
      server: "*"
    - namespace: "!argocd"
      server: "*"
    - namespace: "*"
      server: "*"
