---
apiVersion: v1
kind: Pod
metadata:
  name: good
spec:
  containers:
    - image: busybox:1.35
      name: busybox
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
---
apiVersion: v1
kind: Pod
metadata:
  name: bad
spec:
  containers:
    - image: busybox:latest
      name: busybox
